apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: movie-watchlist
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres.movie-watchlist.svc.cluster.local:5432/movies
